/*
 * Copyright 2012 Michael Roberts
 * All rights reserved.
 *
 *
 * This file is part of xbatch.
 *
 * xbatch is free software: you can redistribute it and/or modify it 
 * under the terms of the GNU Lesser General Public License as published by the 
 * Free Software Foundation, either version 3 of the License, or (at your 
 * option) any later version.
 *
 * xbatch is distributed in the hope that it will be useful, but 
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public 
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License 
 * along with xbatch.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
package com.xtructure.xbatch.batch;

/**
 * @author Luis Guimbarda
 * 
 */
public interface XBatchGenerator {
	/**
	 * @return the next batch created by this generator.
	 */
	public abstract XBatch generateBatch();

	/**
	 * Update the state of this generator based on the given batch. The batch
	 * should have been generated by this and run by a processor.
	 * 
	 * @param batch
	 *            the batch after having been run
	 */
	public abstract void updateGenerator(XBatch batch);

	/**
	 * Revert this generator to its initial state.
	 */
	public void reset();
}
