/*
 * Copyright 2012 Michael Roberts
 * All rights reserved.
 *
 *
 * This file is part of xutil.
 *
 * xutil is free software: you can redistribute it and/or modify it 
 * under the terms of the GNU Lesser General Public License as published by the 
 * Free Software Foundation, either version 3 of the License, or (at your 
 * option) any later version.
 *
 * xutil is distributed in the hope that it will be useful, but 
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public 
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License 
 * along with xutil.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package com.xtructure.xutil.test;

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;

import org.testng.ITestContext;
import org.testng.ITestListener;
import org.testng.ITestResult;

/**
 * A test listener.
 * 
 * @author Peter N&uuml;rnberg
 * 
 * @version 0.9.5
 */
public final class HtmlTestListener
        implements ITestListener
{
    /** The text of the style file generated by this listener. */
    private static final String STYLE_FILE = ".passed { background-color: #00ff00; }\n" //
            + ".skipped { background-color: #ffff00; font-weight: bold; }\n" //
            + ".failed { background-color: #ff0000; color: white; font-weight: bold; }\n" //
            + ".none { background-color: #eeeeee; }\n" //
            + "h1 { font: bold 14pt Arial, sans-serif; }" //
            + "h2 { font: bold 12pt Arial, sans-serif; background-color: #444444; color: white; }" //
            + "table { border-collapse: separate; }\n" //
            + "th { vertical-align: text-top; text-align: left; padding: 1ex; border: thin solid black; background-color: #888888; color: white; }" //
            + "td { vertical-align: text-top; text-align: left; padding: 1ex; border: thin solid black; }";

    /** The root output directory. */
    private File _root = null;

    /** Information about the test suite. */
    private final SuiteInfo _suiteInfo = new SuiteInfo("testsuite");

    /** Creates a new test listener. */
    public HtmlTestListener()
    {
        super();
    }

    /** {@inheritDoc} */
    @Override
	public final void onStart(
            final ITestContext context)
    {
        _root = new File(context.getOutputDirectory()).getParentFile();
        _root.mkdirs();
    }

    /** {@inheritDoc} */
    @Override
	public final void onTestStart(
            final ITestResult result)
    {
        // do nothing
    }

    /** {@inheritDoc} */
    @Override
	public final void onTestSuccess(
            final ITestResult result)
    {
        _suiteInfo.process(result);
    }

    /** {@inheritDoc} */
    @Override
	public final void onTestSkipped(
            final ITestResult result)
    {
        _suiteInfo.process(result);
    }

    /** {@inheritDoc} */
    @Override
	public final void onTestFailedButWithinSuccessPercentage(
            final ITestResult result)
    {
        _suiteInfo.process(result);
    }

    /** {@inheritDoc} */
    @Override
	public final void onTestFailure(
            final ITestResult result)
    {
        _suiteInfo.process(result);
    }

    /** {@inheritDoc} */
    @Override
	public final void onFinish(
            final ITestContext context)
    {
        try
        {
            // write result files
            _suiteInfo.write(_root);

            // write style file
            final PrintWriter out = new PrintWriter( //
                new File(_root, "xtructure-testng.css"));
            out.println(STYLE_FILE);
            out.close();
        }
        catch (IOException e)
        {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
}
